# Generated by Django 6.0.4 on 2026-04-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liderbord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
    ]
