# Generated by Django 6.0.4 on 2026-04-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderbord', '0002_remove_company_description_remove_company_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='distance',
            field=models.PositiveIntegerField(default=100, help_text='Игровая дистанция — чем круче бонус, тем больше', verbose_name='Дистанция (м)'),
        ),
    ]
